openapi: 3.1.0
info:
  title: Vercel API
  description: API specification for Vercel REST API.
  version: "1.0.0"
servers:
  - url: https://api.vercel.com/v1
    description: Vercel API server
paths:
  /projects:
    get:
      summary: List all projects
      security:
        - bearerAuth: {}
      responses:
        '200':
          description: A list of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
    post:
      summary: Create a new project
      security:
        - bearerAuth: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                framework:
                  type: string
      responses:
        '201':
          description: Project created successfully
  /deployments:
    get:
      summary: List all deployments
      security:
        - bearerAuth: {}
      responses:
        '200':
          description: A list of deployments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    state:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
    post:
      summary: Create a new deployment
      security:
        - bearerAuth: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                projectId:
                  type: string
                  example: 'prj_PiNDA1VRbhhwCgJelhkhAOeGtRfB'
                files:
                  type: array
                  items:
                    type: object
                    properties:
                      path:
                        type: string
                      content:
                        type: string
      responses:
        '201':
          description: Deployment created successfully
  /env:
    get:
      summary: List all environment variables
      security:
        - bearerAuth: {}
      responses:
        '200':
          description: A list of environment variables
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    value:
                      type: string
    post:
      summary: Create a new environment variable
      security:
        - bearerAuth: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                value:
                  type: string
      responses:
        '201':
          description: Environment variable created successfully
  /domains:
    get:
      summary: List all domains
      security:
        - bearerAuth: {}
      responses:
        '200':
          description: A list of domains
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    verified:
                      type: boolean
    post:
      summary: Add a new domain
      security:
        - bearerAuth: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Domain added successfully
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
